name: GANDEWALANA

on:
  push:
    branches: [master]

  workflow_dispatch:
    branches: [master]
    inputs:
      job:
        description: "Job to run."
        required: true
        default: "deploy-prod"

jobs:
  laravel-tests:
    name: Laravel Testing

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  deploy-prod:
    name: 🎉 Release to Production!
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'deploy-prod'}}
    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          username: ${{ secrets.SSH_USERNAME }}

          port: ${{ secrets.SSH_PORT }}

          script: cd gandewalana/

            chmod 755 server_prod.sh

            ./server_prod.sh
